[package]
name = "rust_python_fib"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_python_fib"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.0", features = ["extension-module"] }
